language: node_js
node_js:
- "8.10"

env:
- LAMBDA_FUNCTION_NAME=testLambdaFunction

cache:
  directories:
  - node_modules

stages:
- name: test
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: test
    install: npm i && npm i -g serverless
    script: npm run test
  - stage: deploy
    script: sls deploy
