language: node_js
node_js:
- "8.10"

env:
- LAMBDA_FUNCTION_NAME=testLambdaFunction

cache:
  directories:
  - node_modules

before_script:
- npm i -g serverless
- npm i

script:
- npm run test
- sls deploy
