language: node_js
node_js:
- "8.10"

env:
- LAMBDA_FUNCTION_NAME=testLambdaFunction SLS_DEBUG=*

cache:
  directories:
  - node_modules

install: npm i && npm i -g serverless

stages:
- name: test
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: test
    script: npm run test
  - stage: deploy
    script: sls deploy
