service: RemindMeOfThisTweet
plugins:
- serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10

  environment:
    TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
    TWITTER_SCREEN_NAME: ${env:TWITTER_SCREEN_NAME}
    TOPIC_ARN:
      "Fn::Join":
      - ':'
      -
        - "arn:aws:sns:us-east-1"
        - Ref: AWS::AccountId
        - "newReminder"

package:
  exclude:
  - README.md
  - .gitignore
  - .env
  - .env.example
  - .idea/**
  - .git/**

functions:
  fetchTweetsAndSetReminders:
    handler: handler.fetchTweetsAndSetReminders
    events:
    - schedule: rate(10 minutes)
  remind:
    handler: handler.remind
